default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  username: trbrue
  password: pvawv23tq7t3afpganpvweiug
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: YTfield

test:
  <<: *default
  database: YTfield_test

production:
  <<: *default
  adapter: postgresql
  encoding: unicode
  pool: 5

