# config/shakapacker.yml
default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/shakapacker
  cache_manifest: false

development:
  <<: *default
  compile: true
  dev_server:
    host: localhost
    port: 3035
    https: false

test:
  <<: *default
  compile: true

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true
