default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_root_path: public
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  webpack_compile_output: false
  resolved_paths: []
  cache_manifest: false
  extract_css: false
  static_assets_extensions:
    - .jpg
    - .jpeg
    - .png
    - .gif
    - .tiff
    - .ico
    - .svg
    - .eot
    - .otf
    - .ttf
    - .woff
    - .woff2

development:
  <<: *default
  compile: true
  webpack_compile_output: true
  check_yarn_integrity: true
  extract_css: true

test:
  <<: *default
  compile: true
  check_yarn_integrity: true

production:
  <<: *default
  compile: false
  extract_css: true
  cache_manifest: true 
